# Generated by Django 4.0.5 on 2022-06-15 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreC', models.CharField(max_length=60, verbose_name='Nombre campeonato')),
                ('nombreA', models.CharField(max_length=60, verbose_name='Nombre del Auspiciante')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('siglas', models.CharField(max_length=15)),
                ('userTwitter', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('posicion', models.CharField(max_length=30)),
                ('camisa', models.IntegerField(verbose_name='Numero de Camisa')),
                ('sueldo', models.IntegerField(verbose_name='Sueldo')),
                ('equipo_futbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losjugadores', to='futbolec.equipof')),
            ],
        ),
        migrations.CreateModel(
            name='CampeonatoE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=200)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futbol', to='futbolec.campeonato')),
                ('ef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futbol', to='futbolec.equipof')),
            ],
        ),
    ]
